# Deep Q-Network (DQN)
---
In this notebook, you will implement a DQN agent with OpenAI Gym's LunarLander-v2 environment.

### 1. Import the Necessary Packages

In [1]:
import gym
import random
import torch
import numpy as np
from collections import deque, namedtuple
import matplotlib.pyplot as plt
%matplotlib inline

### 2. Instantiate the Environment and Agent

Initialize the environment in the code cell below.

In [2]:
env = gym.make('LunarLander-v2')
env.seed(0)
print('State shape: ', env.observation_space.shape)
print('Number of actions: ', env.action_space.n)

State shape:  (8,)
Number of actions:  4


Please refer to the instructions in `Deep_Q_Network.ipynb` if you would like to write your own DQN agent.  Otherwise, run the code cell below to load the solution files.

In [3]:
from dqn_agent import Agent

agent = Agent(state_size=8, action_size=4, seed=0)

# watch an untrained agent
state = env.reset()
for j in range(200):
    action = agent.act(state)
    env.render()
    state, reward, done, _ = env.step(action)
    if done:
        break 
        
env.close()

In [4]:
agent.qnetwork_local.eval()

QNetwork(
  (fc1): Linear(in_features=8, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=4, bias=True)
)

### 3. Train the Agent with DQN

Run the code cell below to train the agent from scratch.  You are welcome to amend the supplied values of the parameters in the function, to try to see if you can get better performance!

Alternatively, you can skip to the next step below (**4. Watch a Smart Agent!**), to load the saved model weights from a pre-trained agent.

In [49]:
import pdb

In [50]:
def dqn(n_episodes=2000, max_t=1000, eps_start=1.0, eps_end=0.01, eps_decay=0.995):
    """Deep Q-Learning.
    
    Params
    ======
        n_episodes (int): maximum number of training episodes
        max_t (int): maximum number of timesteps per episode
        eps_start (float): starting value of epsilon, for epsilon-greedy action selection
        eps_end (float): minimum value of epsilon
        eps_decay (float): multiplicative factor (per episode) for decreasing epsilon
    """
    scores = []                        # list containing scores from each episode
    scores_window = deque(maxlen=100)  # last 100 scores
    eps = eps_start                    # initialize epsilon
    for i_episode in range(1, n_episodes+1):
        state = env.reset()
        score = 0
        for t in range(max_t):
            action = agent.act(state, eps)
            next_state, reward, done, _ = env.step(action)
            agent.step(state, action, reward, next_state, done)
            state = next_state
            score += reward
            if done:
                break 
        pdb.set_trace()
        scores_window.append(score)       # save most recent score
        scores.append(score)              # save most recent score
        eps = max(eps_end, eps_decay*eps) # decrease epsilon
        print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)), end="")
        if i_episode % 100 == 0:
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
        if np.mean(scores_window)>=200.0:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i_episode-100, np.mean(scores_window)))
            torch.save(agent.qnetwork_local.state_dict(), 'checkpoint.pth')
            break
    return scores

scores = dqn()

# plot the scores
fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(np.arange(len(scores)), scores)
plt.ylabel('Score')
plt.xlabel('Episode #')
plt.show()

> <ipython-input-50-4b71072aa82e>(27)dqn()
-> scores_window.append(score)       # save most recent score
(Pdb) action
1
(Pdb) l
 22  	            state = next_state
 23  	            score += reward
 24  	            if done:
 25  	                break
 26  	        pdb.set_trace()
 27  ->	        scores_window.append(score)       # save most recent score
 28  	        scores.append(score)              # save most recent score
 29  	        eps = max(eps_end, eps_decay*eps) # decrease epsilon
 30  	        print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)), end="")
 31  	        if i_episode % 100 == 0:
 32  	            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
(Pdb) s
> <ipython-input-50-4b71072aa82e>(28)dqn()
-> scores.append(score)              # save most recent score
(Pdb) ?

Documented commands (type help <topic>):
EOF    c          d        h         list      q        rv       undisplay
a      cl 

(Pdb) agent.qnetwork_target(next_states)
*** NameError: name 'next_states' is not defined
(Pdb) states
*** NameError: name 'states' is not defined
(Pdb) exps = agent.memory.sample()
(Pdb) exps
(tensor([[ 6.0966e-03,  1.3830e+00,  2.1713e-01, -4.1300e-01, -9.8569e-03,
         -7.0632e-02,  0.0000e+00,  0.0000e+00],
        [-4.3087e-02,  8.9639e-01, -1.8141e-01, -9.1193e-01,  3.1014e-01,
          6.5574e-02,  0.0000e+00,  0.0000e+00],
        [-1.6992e-01,  1.5441e+00, -4.7929e-01, -2.0485e-01,  2.4759e-01,
          1.5405e-01,  0.0000e+00,  0.0000e+00],
        [ 1.5873e-01,  1.5116e+00,  4.5047e-01, -1.0888e-01, -1.3755e-01,
         -1.5146e-02,  0.0000e+00,  0.0000e+00],
        [-2.2511e-03,  6.5165e-01,  3.2420e-01, -9.8647e-01, -5.3010e-01,
         -2.3200e-01,  0.0000e+00,  0.0000e+00],
        [-1.9436e-01,  1.2574e+00, -7.4399e-01, -4.3366e-01,  2.5142e-01,
          1.7521e-01,  0.0000e+00,  0.0000e+00],
        [ 3.6542e-01,  1.1775e+00,  7.6149e-01, -5.1593e-01, -1.3705

(Pdb) exps.shape
*** AttributeError: 'tuple' object has no attribute 'shape'
(Pdb) len(exps)
5
(Pdb) states, actions, rewards, next_states, dones = exps
(Pdb) states
tensor([[ 6.0966e-03,  1.3830e+00,  2.1713e-01, -4.1300e-01, -9.8569e-03,
         -7.0632e-02,  0.0000e+00,  0.0000e+00],
        [-4.3087e-02,  8.9639e-01, -1.8141e-01, -9.1193e-01,  3.1014e-01,
          6.5574e-02,  0.0000e+00,  0.0000e+00],
        [-1.6992e-01,  1.5441e+00, -4.7929e-01, -2.0485e-01,  2.4759e-01,
          1.5405e-01,  0.0000e+00,  0.0000e+00],
        [ 1.5873e-01,  1.5116e+00,  4.5047e-01, -1.0888e-01, -1.3755e-01,
         -1.5146e-02,  0.0000e+00,  0.0000e+00],
        [-2.2511e-03,  6.5165e-01,  3.2420e-01, -9.8647e-01, -5.3010e-01,
         -2.3200e-01,  0.0000e+00,  0.0000e+00],
        [-1.9436e-01,  1.2574e+00, -7.4399e-01, -4.3366e-01,  2.5142e-01,
          1.7521e-01,  0.0000e+00,  0.0000e+00],
        [ 3.6542e-01,  1.1775e+00,  7.6149e-01, -5.1593e-01, -1.3705e-01,
         -1.5712e-01, 

(Pdb) next_states.shape
torch.Size([64, 8])
(Pdb) qnxt = agent.qnetwork_target(next_states)
(Pdb) qnxt.size
<built-in method size of Tensor object at 0x0000021D09D50D80>
(Pdb) qnxt
tensor([[-7.6255e-01, -6.5656e-01,  1.2808e-01, -7.9559e-01],
        [-8.1147e-01, -9.5351e-01, -3.8339e-03, -7.9012e-01],
        [-5.7803e-01, -8.2411e-01, -1.5337e-01, -3.9225e-01],
        [-8.0277e-01, -5.4181e-01, -1.0770e-01, -7.0364e-01],
        [-1.3801e+00, -8.4314e-01, -4.7596e-01, -1.2253e+00],
        [-6.5929e-01, -9.1847e-01, -1.3469e-01, -4.8043e-01],
        [-1.0432e+00, -5.9242e-01,  3.1152e-02, -1.0348e+00],
        [-1.1509e+00, -7.6306e-01, -1.0010e-01, -1.1649e+00],
        [-9.0782e-01, -6.8485e-01,  3.7526e-02, -9.1933e-01],
        [-2.3293e+00, -1.0873e+00, -1.4693e+00, -1.8580e+00],
        [-8.5909e-01, -5.8156e-01,  3.2812e-02, -8.4297e-01],
        [-5.2436e-01, -6.4652e-01, -1.9113e-01, -3.5277e-01],
        [-1.7466e+00, -2.0224e+00, -1.9633e+00, -9.5808e-01],
        [-4.7

(Pdb) lqag = agent.qnetwork_local(states)
(Pdb) lqag.size()
torch.Size([64, 4])
(Pdb) lqag[1,:]
tensor([-0.5405, -1.7728,  1.9306, -1.2535], grad_fn=<SliceBackward>)
(Pdb) lqag[1]
tensor([-0.5405, -1.7728,  1.9306, -1.2535], grad_fn=<SelectBackward>)
(Pdb) lqag[1].sum()
tensor(-1.6362, grad_fn=<SumBackward0>)
(Pdb) lqag.gather(1, actions)
tensor([[ -0.4736],
        [ -0.5405],
        [ -1.9309],
        [ -0.9552],
        [ -2.7738],
        [ -0.3571],
        [  1.2218],
        [ -1.0693],
        [ -1.8128],
        [ -7.0004],
        [ -0.9802],
        [ -1.4320],
        [ -2.1784],
        [ -1.4248],
        [ -0.6030],
        [-16.3591],
        [ -1.2763],
        [ -5.9096],
        [ -4.2970],
        [ -1.2719],
        [ -6.1727],
        [ -2.7181],
        [ -6.7118],
        [ -3.8659],
        [ -4.0901],
        [ -0.9469],
        [ -0.7936],
        [ -0.6786],
        [ -0.1471],
        [  0.1700],
        [-10.0394],
        [ -0.5723],
        [ -0.8167],

(Pdb) lagq
*** NameError: name 'lagq' is not defined
(Pdb) lqag.max(1)
torch.return_types.max(
values=tensor([  1.1932,   1.9306,  -0.0241,  -0.2488,   0.7819,   0.5164,   1.2218,
          1.8603,   1.1967,  -1.6772,   0.5550,   0.0238,  -2.1784,   0.4122,
          1.6441,  -6.6180,  -0.1323,  -5.7148,  -1.3596,   1.6246,  -3.5084,
         -2.7181,  -3.3217,  -3.3669,  -2.3796,   1.3779,   2.0625,   0.7700,
         -0.1471,   0.1700,  -2.9760,   1.2099,   1.2501,   1.8542,  -0.0744,
          0.3758,   0.8694,   1.4412,  -0.4494,   0.9807,   0.4317,  -3.5570,
          0.3845,   1.4821,   0.9712,   0.8260,  -0.0983,  -2.8456,  -4.3711,
        -19.9973,  -2.5666,  -0.6032,   1.9409,   2.0524,  -3.7179, -19.2054,
          1.2433,   2.0122,  -0.8207,  -4.6519,   0.5877,  -0.9366,   0.6806,
          1.8608], grad_fn=<MaxBackward0>),
indices=tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 2, 3, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 1, 2,

BdbQuit: 

### 4. Watch a Smart Agent!

In the next code cell, you will load the trained weights from file to watch a smart agent!

In [4]:
# load the weights from file
agent.qnetwork_local.load_state_dict(torch.load('checkpoint.pth'))

for i in range(3):
    state = env.reset()
    for j in range(200):
        action = agent.act(state)
        env.render()
        state, reward, done, _ = env.step(action)
        if done:
            break 
            
env.close()

### 5. Explore

In this exercise, you have implemented a DQN agent and demonstrated how to use it to solve an OpenAI Gym environment.  To continue your learning, you are encouraged to complete any (or all!) of the following tasks:
- Amend the various hyperparameters and network architecture to see if you can get your agent to solve the environment faster.  Once you build intuition for the hyperparameters that work well with this environment, try solving a different OpenAI Gym task with discrete actions!
- You may like to implement some improvements such as prioritized experience replay, Double DQN, or Dueling DQN! 
- Write a blog post explaining the intuition behind the DQN algorithm and demonstrating how to use it to solve an RL environment of your choosing.  